name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "second branch"
      - uses: actions/checkout@v2
        # Step's name
      - name: Setup PHP
        # Action gives to setup the PHP environment to test application
        # https://github.com/shivammathur/setup-php
        uses: shivammathur/setup-php@v2
        with:
          # Specify the PHP version
          php-version: '7.4'
          
          
          
      - name: Lines Of Code Alert
  # You may pin to the exact commit or the version.
  # uses: NachoVazquez/loc-alarm@d1234ffd3e8bbd2d0d782b43f3102dc323b55850
  uses: NachoVazquez/loc-alarm@v1
  with:
    # The file or folder to process
    fileOrFolderToProcess: # optional, default is .
    # A list of directories to ignore. Supports glob patterns.
    filesAndFoldersToIgnore: # optional, default is ["node_modules", ".git", "dist", ".github"]
    # The maximum number of LOC for the sum of files
    maxCount: 1
    
  -name: Install
  run: make install
  
    - name: Run linter
        # Run Linter
        run: make lint
        # Publish code coverage on Code Climate
        # https://github.com/paambaati/codeclimate-action
      - name: Run test & publish code coverage
        uses: paambaati/codeclimate-action@v2.6.0
        # Add Code Climate secret key
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: make test-coverage
          coverageLocations: ${{github.workplace}}/build/logs/clover.xml:clover
          debug: true
